# Generated by Django 4.2.1 on 2023-11-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0005_topic_level_topic_lft_topic_parent_topic_rght_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
