# Generated by Django 4.2.1 on 2023-11-27 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0006_topic_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='notebooks.topic'),
            preserve_default=False,
        ),
    ]
